In [1]:
import numpy as np 
from MPHP_weekly import MPHP
from MHP import MHP

In [4]:
m = np.array([0.2, 0.0, 0.0])
a = np.array([[0.1, 0.0, 0.0], 
              [0.9, 0.0, 0.0],
              [0.0, 0.9, 0.0]])
w = 3.1
md=np.array([2,2,1,1,1,0,0])
PP = MPHP(mu=m, alpha=a, omega=w, mu_day=md)
datap = PP.generate_seq(180)

P = MHP(mu=m, alpha=a, omega=w)
P.generate_seq(180)

Max eigenvalue: 0.10000


146

In [22]:
mhat = np.random.uniform(0,1, size=3)
ahat = np.random.uniform(0,1, size=(3,3))
w = 3.

alpha0, mu0 = P.EM(ahat, mhat, w)

After ITER 0 (old: -10000.000 new: 0.033)
 terms 43.7870, 41.9259, 41.0741
After ITER 10 (old: 0.033 new: -1.144)
 terms -46.7441, 34.7630, 48.2370
Reached stopping criterion. (Old: -1.144 New: -1.142)


In [8]:
mhatday = np.random.uniform(0.8, 1.2, size=7)

alpha, mu, mu_day = PP.EM(ahat, mhat, mhatday, w)

After ITER 0 (old: -10000.000 new: -0.165)
 terms 74.9226, 50.4778, 99.0710
After ITER 10 (old: -0.165 new: -0.743)
 terms -3.6529, 28.0270, 104.8170
Reached stopping criterion. (Old: -0.743 New: -0.739)


In [23]:
#Non periodic MHP
print('alpha\n', np.round(alpha0, 2))
print('mu\n', np.round(mu0, 2))

alpha
 [[ 0.    0.    0.  ]
 [ 0.77  0.    0.  ]
 [ 0.    0.68  0.12]]
mu
 [ 0.21  0.    0.  ]


In [24]:
# Periodic MHP
print('alpha\n', np.round(alpha, 2))
print('mu\n', np.round(mu, 2))
print('mu_day\n', np.round(mu_day, 2))

alpha
 [[ 0.02  0.03  0.05]
 [ 1.1   0.05  0.  ]
 [ 0.    0.85  0.04]]
mu
 [ 0.16  0.    0.  ]
mu_day
 [ 1.95  1.8   1.2   0.98  1.08  0.    0.  ]
